### ISSUE TITLE
Extract all icons in a web link

### ISSUE THREAD

**Issue by beastybeast** [lordelph/icofileloader#15]
Hi

Right now it seam as if it is only possible to get individual images in an ico file when it is placed locally as a file (fromFile or from). I like to get it from a remote url. So I guess that I have to retrieve the file first and store it locally.

Nice to have it as a single function like with extractIcon?

/Benny

**Comment by lordelph** [comment]
As long as you have [allow-url-fopen](https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) enabled you should be able to read icons from an URL just as easily as a file. Is that not working for you?

**Comment by beastybeast** [comment]
Yes - sorry it works fine ;-)

The documentation got me on the wrong track.

Is it not possible to render a specific index icon. It only seam possible to specify size and it will then select based on this?

NB: Sorry if this is also a stupid question.

**Comment by beastybeast** [comment]
It seam to work with $icon->offsetGet($index)
