### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by offsky** [lordelph/icofileloader#20]
I am upgrading my project to PHP 8.1 and am encountering warnings in your library. Here is one example:

> Deprecated: Return type of Elphin\IcoFileLoader\Icon::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

The rest of the warnings are similar. The quick fix is to add the return types to the functions in question.  Here are my changes. Hope this helps!
[Icon.php.zip](https://github.com/lordelph/icofileloader/files/9384147/Icon.php.zip)

**Comment by offsky** [comment]
Sorry, I forgot to check the pull requests before making this issue and just noticed that this is already being discussed: https://github.com/lordelph/icofileloader/pull/19

**Comment by lordelph** [comment]
I've now made a new release of a php8 compatible version 3.x.x
